// <auto-generated />
using System;
using Assessment.Rapor.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assessment.Rapor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230723215804_RaporIcerik")]
    partial class RaporIcerik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assessment.Rapor.Api.Models.RaporIcerik", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RaporlarId")
                        .HasColumnType("uuid");

                    b.Property<int>("TelefonSayisi")
                        .HasColumnType("integer");

                    b.HasKey("UUID");

                    b.HasIndex("RaporlarId");

                    b.ToTable("RaporIcerik");
                });

            modelBuilder.Entity("Assessment.Rapor.Api.Models.Raporlar", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RaporDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UUID");

                    b.ToTable("Raporlar");
                });

            modelBuilder.Entity("Assessment.Rapor.Api.Models.RaporIcerik", b =>
                {
                    b.HasOne("Assessment.Rapor.Api.Models.Raporlar", "Raporlar")
                        .WithMany("RaporIcerigi")
                        .HasForeignKey("RaporlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raporlar");
                });

            modelBuilder.Entity("Assessment.Rapor.Api.Models.Raporlar", b =>
                {
                    b.Navigation("RaporIcerigi");
                });
#pragma warning restore 612, 618
        }
    }
}
