// <auto-generated />
using System;
using Assessment.Kisiler.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assessment.Kisiler.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assessment.Kisiler.Api.Models.IletisimBilgisi", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BilgiTipi")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KisiId")
                        .HasColumnType("uuid");

                    b.HasKey("UUID");

                    b.HasIndex("KisiId");

                    b.ToTable("IletisimBilgisi");

                    b.HasData(
                        new
                        {
                            UUID = new Guid("b39be259-0623-4c6e-b6a5-b4e6f74d6457"),
                            BilgiTipi = 1,
                            Icerik = "Amanda.Youngs@Edgewire.com",
                            KisiId = new Guid("da1319dd-4e81-4f50-9d4b-846b83abf0a3")
                        },
                        new
                        {
                            UUID = new Guid("4e551c2c-c0ec-473f-89a7-ced43d2cdbfb"),
                            BilgiTipi = 1,
                            Icerik = "Jarrad.Agglione@Devshare.com",
                            KisiId = new Guid("ecadbd93-39f9-43a7-9c76-eea2be8686b0")
                        },
                        new
                        {
                            UUID = new Guid("dbb87f77-0f32-4872-a393-c7fef63a012c"),
                            BilgiTipi = 1,
                            Icerik = "Kenyon.Waylen@Twitterwire.com",
                            KisiId = new Guid("136ce6bf-5eeb-468d-ba30-bb7ce1843cd0")
                        },
                        new
                        {
                            UUID = new Guid("e5762cb6-b204-4395-8de4-5e9362abb948"),
                            BilgiTipi = 1,
                            Icerik = "Linea.Duigan@Fivechat.com",
                            KisiId = new Guid("36aec2e1-3aa7-4d9e-91f3-d0efbee71b87")
                        },
                        new
                        {
                            UUID = new Guid("f1bb3f17-940a-4c33-a391-bc01d16fe699"),
                            BilgiTipi = 1,
                            Icerik = "Lock.Molyneaux@Feedfish.com",
                            KisiId = new Guid("8b746864-eff7-49f6-ac4e-79a48fbf7c39")
                        },
                        new
                        {
                            UUID = new Guid("3e3b853e-a4e9-4283-b272-505ef422920c"),
                            BilgiTipi = 0,
                            Icerik = "584-128-3271",
                            KisiId = new Guid("da1319dd-4e81-4f50-9d4b-846b83abf0a3")
                        },
                        new
                        {
                            UUID = new Guid("05de750b-a805-499e-990d-b018e008001d"),
                            BilgiTipi = 0,
                            Icerik = "410-174-8583",
                            KisiId = new Guid("136ce6bf-5eeb-468d-ba30-bb7ce1843cd0")
                        },
                        new
                        {
                            UUID = new Guid("538bf86e-3f2e-4c1b-bed7-37834a0ab63f"),
                            BilgiTipi = 0,
                            Icerik = "744-961-7350",
                            KisiId = new Guid("8b746864-eff7-49f6-ac4e-79a48fbf7c39")
                        },
                        new
                        {
                            UUID = new Guid("76c33942-34ef-4cdd-864b-9c6eb0295b91"),
                            BilgiTipi = 2,
                            Icerik = "İstanbul",
                            KisiId = new Guid("da1319dd-4e81-4f50-9d4b-846b83abf0a3")
                        },
                        new
                        {
                            UUID = new Guid("c20b4040-ca01-4441-a983-8c49cfdc190e"),
                            BilgiTipi = 2,
                            Icerik = "İstanbul",
                            KisiId = new Guid("ecadbd93-39f9-43a7-9c76-eea2be8686b0")
                        },
                        new
                        {
                            UUID = new Guid("4bf05cab-47ca-4857-bb44-9eff101eb420"),
                            BilgiTipi = 2,
                            Icerik = "İzmir",
                            KisiId = new Guid("136ce6bf-5eeb-468d-ba30-bb7ce1843cd0")
                        },
                        new
                        {
                            UUID = new Guid("ceea15f2-74e5-4c4e-bf41-8c12c776d9ea"),
                            BilgiTipi = 2,
                            Icerik = "İstanbul",
                            KisiId = new Guid("36aec2e1-3aa7-4d9e-91f3-d0efbee71b87")
                        },
                        new
                        {
                            UUID = new Guid("8eb0abe2-27d8-4b6a-9a88-2338c918c037"),
                            BilgiTipi = 2,
                            Icerik = "İstanbul",
                            KisiId = new Guid("8b746864-eff7-49f6-ac4e-79a48fbf7c39")
                        });
                });

            modelBuilder.Entity("Assessment.Kisiler.Api.Models.Kisi", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.ToTable("Kisiler");

                    b.HasData(
                        new
                        {
                            UUID = new Guid("da1319dd-4e81-4f50-9d4b-846b83abf0a3"),
                            Ad = "Amanda",
                            Firma = "Edgewire",
                            Soyad = "Youngs"
                        },
                        new
                        {
                            UUID = new Guid("ecadbd93-39f9-43a7-9c76-eea2be8686b0"),
                            Ad = "Jarrad",
                            Firma = "Devshare",
                            Soyad = "Agglione"
                        },
                        new
                        {
                            UUID = new Guid("136ce6bf-5eeb-468d-ba30-bb7ce1843cd0"),
                            Ad = "Kenyon",
                            Firma = "Twitterwire",
                            Soyad = "Waylen"
                        },
                        new
                        {
                            UUID = new Guid("36aec2e1-3aa7-4d9e-91f3-d0efbee71b87"),
                            Ad = "Linea",
                            Firma = "Fivechat",
                            Soyad = "Duigan"
                        },
                        new
                        {
                            UUID = new Guid("8b746864-eff7-49f6-ac4e-79a48fbf7c39"),
                            Ad = "Lock",
                            Firma = "Feedfish",
                            Soyad = "Molyneaux"
                        },
                        new
                        {
                            UUID = new Guid("cf9b359d-8097-48c2-8a74-85619aecc868"),
                            Ad = "Kandy",
                            Firma = "Rhyzio",
                            Soyad = "Hairs"
                        },
                        new
                        {
                            UUID = new Guid("77c6a1e7-f295-497f-9d4b-31b18c8d73f6"),
                            Ad = "Priscella",
                            Firma = "Photobean",
                            Soyad = "Eul"
                        },
                        new
                        {
                            UUID = new Guid("3f174232-8ecd-4908-a239-d080e6749e97"),
                            Ad = "Therine",
                            Firma = "Quire",
                            Soyad = "Bancroft"
                        },
                        new
                        {
                            UUID = new Guid("e128ad20-dc81-4cd1-81de-e5e7d9dfe53f"),
                            Ad = "Pincus",
                            Firma = "Riffwire",
                            Soyad = "Portingale"
                        },
                        new
                        {
                            UUID = new Guid("b7e13b1a-be3f-4d7b-b170-38d696e47d0b"),
                            Ad = "Melva",
                            Firma = "Thoughtbeat",
                            Soyad = "Simnor"
                        },
                        new
                        {
                            UUID = new Guid("5e0adc61-cc87-4ad3-9462-5d1364dbe598"),
                            Ad = "Reed",
                            Firma = "Livetube",
                            Soyad = "Saynor"
                        },
                        new
                        {
                            UUID = new Guid("c90207e1-352a-4dbd-96a4-1cb914a5b936"),
                            Ad = "Kyrstin",
                            Firma = "Rhyzio",
                            Soyad = "Yea"
                        },
                        new
                        {
                            UUID = new Guid("684fc466-b6de-4214-a4db-856c63703eb6"),
                            Ad = "Rene",
                            Firma = "Shufflebeat",
                            Soyad = "Faley"
                        },
                        new
                        {
                            UUID = new Guid("1bd60b22-87bb-4163-b47c-07426928e89f"),
                            Ad = "Rosalie",
                            Firma = "Flashpoint",
                            Soyad = "O'Neill"
                        },
                        new
                        {
                            UUID = new Guid("b97cb918-e9c2-42d2-8934-5cd420a0d86c"),
                            Ad = "Carlota",
                            Firma = "Photobug",
                            Soyad = "Semble"
                        },
                        new
                        {
                            UUID = new Guid("ed7cf807-35d3-481b-8525-540a02b4f68d"),
                            Ad = "Dario",
                            Firma = "Camido",
                            Soyad = "Jobey"
                        },
                        new
                        {
                            UUID = new Guid("a0bf6b9e-05d6-4675-8d25-0b72aa0a0735"),
                            Ad = "Prescott",
                            Firma = "Twitterwire",
                            Soyad = "Tinsey"
                        },
                        new
                        {
                            UUID = new Guid("c9adfe33-ac0f-438e-b4bf-149a0b68e809"),
                            Ad = "Romeo",
                            Firma = "Quamba",
                            Soyad = "Paterno"
                        },
                        new
                        {
                            UUID = new Guid("9a70a61b-d2db-4b1a-b3d3-1cb70eff0239"),
                            Ad = "Kristofer",
                            Firma = "Mycat",
                            Soyad = "Salzberg"
                        },
                        new
                        {
                            UUID = new Guid("adaedde8-a3ae-4b1f-8130-70dce3ab1b11"),
                            Ad = "Dulcie",
                            Firma = "Pixoboo",
                            Soyad = "Heintze"
                        });
                });

            modelBuilder.Entity("Assessment.Kisiler.Api.Models.IletisimBilgisi", b =>
                {
                    b.HasOne("Assessment.Kisiler.Api.Models.Kisi", "Kisi")
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");
                });

            modelBuilder.Entity("Assessment.Kisiler.Api.Models.Kisi", b =>
                {
                    b.Navigation("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
